-- NERV colorscheme. See lua/nerv/palette.lua for the colors themselves.
-- Loaded by colors/nerv.lua, i.e. `:colorscheme nerv`.

local c = require("nerv.palette")

local M = {}

local function groups()
  return {
    -- editor ---------------------------------------------------------------
    Normal = { fg = c.fg, bg = c.bg },
    NormalNC = { fg = c.fg, bg = c.bg },
    NormalFloat = { fg = c.fg, bg = c.bg_light },
    FloatBorder = { fg = c.brown, bg = c.bg_light },
    FloatTitle = { fg = c.accent, bg = c.bg_light, bold = true },
    ColorColumn = { bg = c.bg_light },
    Conceal = { fg = c.muted },
    Cursor = { fg = c.bg, bg = c.accent },
    lCursor = { link = "Cursor" },
    CursorIM = { link = "Cursor" },
    CursorLine = { bg = c.cursorline },
    CursorColumn = { bg = c.cursorline },
    CursorLineNr = { fg = c.accent, bold = true },
    LineNr = { fg = c.gutter },
    LineNrAbove = { fg = c.gutter },
    LineNrBelow = { fg = c.gutter },
    Directory = { fg = c.blue },
    EndOfBuffer = { fg = c.bg },
    ErrorMsg = { fg = c.red, bold = true },
    WinSeparator = { fg = c.border, bg = c.bg },
    VertSplit = { link = "WinSeparator" },
    Folded = { fg = c.fg_dark, bg = c.bg_light },
    FoldColumn = { fg = c.muted, bg = c.bg },
    SignColumn = { fg = c.muted, bg = c.bg },
    IncSearch = { fg = c.bg, bg = c.bright_yellow, bold = true },
    CurSearch = { fg = c.bg, bg = c.bright_yellow, bold = true },
    Search = { fg = c.bg, bg = c.accent },
    Substitute = { fg = c.bg, bg = c.red },
    MatchParen = { fg = c.bright_yellow, bold = true, underline = true },
    ModeMsg = { fg = c.fg_light, bold = true },
    MsgArea = { fg = c.fg },
    MsgSeparator = { fg = c.border, bg = c.bg },
    MoreMsg = { fg = c.green },
    NonText = { fg = c.nontext },
    Pmenu = { fg = c.fg_light, bg = c.bg_light },
    PmenuSel = { fg = c.fg_bright, bg = c.sel, bold = true },
    PmenuSbar = { bg = c.bg_light },
    PmenuThumb = { bg = c.muted },
    PmenuMatch = { fg = c.accent, bg = c.bg_light },
    PmenuMatchSel = { fg = c.accent, bg = c.sel, bold = true },
    Question = { fg = c.green },
    QuickFixLine = { bg = c.sel, bold = true },
    SpecialKey = { fg = c.muted },
    SpellBad = { sp = c.red, undercurl = true },
    SpellCap = { sp = c.yellow, undercurl = true },
    SpellLocal = { sp = c.cyan, undercurl = true },
    SpellRare = { sp = c.magenta, undercurl = true },
    StatusLine = { fg = c.fg, bg = c.bg_dark },
    StatusLineNC = { fg = c.muted, bg = c.bg_dark },
    TabLine = { fg = c.fg_dark, bg = c.bg_dark },
    TabLineFill = { bg = c.bg_darker },
    TabLineSel = { fg = c.bg, bg = c.accent, bold = true },
    Title = { fg = c.accent, bold = true },
    Visual = { bg = c.sel },
    VisualNOS = { bg = c.sel },
    WarningMsg = { fg = c.yellow },
    Whitespace = { fg = c.nontext },
    WildMenu = { bg = c.sel },
    WinBar = { fg = c.fg_light, bg = c.bg, bold = true },
    WinBarNC = { fg = c.muted, bg = c.bg },

    -- syntax ---------------------------------------------------------------
    Comment = { fg = c.muted, italic = true },
    Constant = { fg = c.magenta },
    String = { fg = c.green },
    Character = { fg = c.bright_green },
    Number = { fg = c.bright_magenta },
    Float = { fg = c.bright_magenta },
    Boolean = { fg = c.orange },
    Identifier = { fg = c.fg },
    Function = { fg = c.yellow },
    Statement = { fg = c.orange },
    Conditional = { fg = c.orange },
    Repeat = { fg = c.orange },
    Label = { fg = c.orange },
    Operator = { fg = c.fg_light },
    Keyword = { fg = c.orange },
    Exception = { fg = c.red },
    PreProc = { fg = c.magenta },
    Include = { fg = c.magenta },
    Define = { fg = c.magenta },
    Macro = { fg = c.magenta },
    PreCondit = { fg = c.magenta },
    Type = { fg = c.cyan },
    StorageClass = { fg = c.cyan },
    Structure = { fg = c.cyan },
    Typedef = { fg = c.cyan },
    Special = { fg = c.bright_yellow },
    SpecialChar = { fg = c.bright_yellow },
    Tag = { fg = c.orange },
    Delimiter = { fg = c.fg_dark },
    SpecialComment = { fg = c.muted, bold = true },
    Debug = { fg = c.red },
    Underlined = { underline = true },
    Ignore = { fg = c.muted },
    Error = { fg = c.red },
    Todo = { fg = c.bg, bg = c.yellow, bold = true },
    Added = { fg = c.green },
    Changed = { fg = c.blue },
    Removed = { fg = c.red },

    -- diffs ----------------------------------------------------------------
    DiffAdd = { bg = c.diff_add },
    DiffChange = { bg = c.diff_change },
    DiffDelete = { bg = c.diff_delete },
    DiffText = { bg = c.diff_text },

    -- diagnostics ----------------------------------------------------------
    DiagnosticError = { fg = c.red },
    DiagnosticWarn = { fg = c.yellow },
    DiagnosticInfo = { fg = c.blue },
    DiagnosticHint = { fg = c.cyan },
    DiagnosticOk = { fg = c.green },
    DiagnosticVirtualTextError = { fg = c.red, bg = c.diff_delete },
    DiagnosticVirtualTextWarn = { fg = c.yellow, bg = c.bg_light },
    DiagnosticVirtualTextInfo = { fg = c.blue, bg = c.diff_change },
    DiagnosticVirtualTextHint = { fg = c.cyan, bg = c.diff_change },
    DiagnosticVirtualTextOk = { fg = c.green, bg = c.diff_add },
    DiagnosticUnderlineError = { sp = c.red, undercurl = true },
    DiagnosticUnderlineWarn = { sp = c.yellow, undercurl = true },
    DiagnosticUnderlineInfo = { sp = c.blue, undercurl = true },
    DiagnosticUnderlineHint = { sp = c.cyan, undercurl = true },
    DiagnosticUnderlineOk = { sp = c.green, undercurl = true },
    DiagnosticDeprecated = { fg = c.muted, strikethrough = true },
    DiagnosticUnnecessary = { fg = c.muted },

    -- lsp ------------------------------------------------------------------
    LspReferenceText = { bg = c.reference },
    LspReferenceRead = { bg = c.reference },
    LspReferenceWrite = { bg = c.reference, underline = true },
    LspInlayHint = { fg = c.muted, bg = c.bg_light, italic = true },
    LspCodeLens = { fg = c.muted, italic = true },
    LspSignatureActiveParameter = { fg = c.accent, bold = true },
    LspInfoBorder = { fg = c.brown, bg = c.bg_light },

    -- treesitter -----------------------------------------------------------
    ["@variable"] = { fg = c.fg },
    ["@variable.builtin"] = { fg = c.bright_red, italic = true },
    ["@variable.parameter"] = { fg = c.bright_blue },
    ["@variable.member"] = { fg = c.fg_light },
    ["@constant"] = { fg = c.magenta },
    ["@constant.builtin"] = { fg = c.bright_magenta },
    ["@constant.macro"] = { fg = c.magenta },
    ["@module"] = { fg = c.cyan },
    ["@module.builtin"] = { fg = c.cyan, italic = true },
    ["@label"] = { fg = c.orange },
    ["@string"] = { fg = c.green },
    ["@string.documentation"] = { fg = c.green, italic = true },
    ["@string.regexp"] = { fg = c.bright_green },
    ["@string.escape"] = { fg = c.bright_yellow, bold = true },
    ["@string.special"] = { fg = c.bright_yellow },
    ["@string.special.url"] = { fg = c.blue, underline = true },
    ["@character"] = { fg = c.bright_green },
    ["@character.special"] = { fg = c.bright_yellow },
    ["@boolean"] = { fg = c.orange },
    ["@number"] = { fg = c.bright_magenta },
    ["@number.float"] = { fg = c.bright_magenta },
    ["@type"] = { fg = c.cyan },
    ["@type.builtin"] = { fg = c.bright_cyan },
    ["@type.definition"] = { fg = c.cyan },
    ["@attribute"] = { fg = c.magenta },
    ["@property"] = { fg = c.fg_light },
    ["@function"] = { fg = c.yellow },
    ["@function.builtin"] = { fg = c.bright_yellow },
    ["@function.macro"] = { fg = c.magenta },
    ["@function.method"] = { fg = c.yellow },
    ["@constructor"] = { fg = c.bright_cyan },
    ["@operator"] = { fg = c.fg_light },
    ["@keyword"] = { fg = c.orange },
    ["@keyword.function"] = { fg = c.orange },
    ["@keyword.operator"] = { fg = c.orange },
    ["@keyword.return"] = { fg = c.bright_red },
    ["@keyword.exception"] = { fg = c.red },
    ["@keyword.import"] = { fg = c.magenta },
    ["@keyword.directive"] = { fg = c.magenta },
    ["@punctuation.delimiter"] = { fg = c.fg_dark },
    ["@punctuation.bracket"] = { fg = c.fg_dark },
    ["@punctuation.special"] = { fg = c.bright_yellow },
    ["@comment"] = { fg = c.muted, italic = true },
    ["@comment.error"] = { fg = c.bg, bg = c.red, bold = true },
    ["@comment.warning"] = { fg = c.bg, bg = c.yellow, bold = true },
    ["@comment.todo"] = { fg = c.bg, bg = c.accent, bold = true },
    ["@comment.note"] = { fg = c.bg, bg = c.cyan, bold = true },
    ["@markup.strong"] = { bold = true },
    ["@markup.italic"] = { italic = true },
    ["@markup.strikethrough"] = { strikethrough = true },
    ["@markup.underline"] = { underline = true },
    ["@markup.heading"] = { fg = c.accent, bold = true },
    ["@markup.heading.1"] = { fg = c.accent, bold = true },
    ["@markup.heading.2"] = { fg = c.yellow, bold = true },
    ["@markup.heading.3"] = { fg = c.bright_yellow, bold = true },
    ["@markup.heading.4"] = { fg = c.fg_light, bold = true },
    ["@markup.heading.5"] = { fg = c.fg_dark, bold = true },
    ["@markup.heading.6"] = { fg = c.muted, bold = true },
    ["@markup.quote"] = { fg = c.fg_dark, italic = true },
    ["@markup.math"] = { fg = c.cyan },
    ["@markup.link"] = { fg = c.blue },
    ["@markup.link.label"] = { fg = c.cyan },
    ["@markup.link.url"] = { fg = c.blue, underline = true },
    ["@markup.raw"] = { fg = c.bright_green },
    ["@markup.raw.block"] = { fg = c.fg_light, bg = c.bg_light },
    ["@markup.list"] = { fg = c.accent },
    ["@markup.list.checked"] = { fg = c.green },
    ["@markup.list.unchecked"] = { fg = c.muted },
    ["@diff.plus"] = { fg = c.green },
    ["@diff.minus"] = { fg = c.red },
    ["@diff.delta"] = { fg = c.blue },
    ["@tag"] = { fg = c.orange },
    ["@tag.builtin"] = { fg = c.bright_red },
    ["@tag.attribute"] = { fg = c.yellow, italic = true },
    ["@tag.delimiter"] = { fg = c.fg_dark },

    -- lsp semantic tokens --------------------------------------------------
    ["@lsp.type.class"] = { link = "@type" },
    ["@lsp.type.comment"] = {},
    ["@lsp.type.decorator"] = { link = "@attribute" },
    ["@lsp.type.enum"] = { link = "@type" },
    ["@lsp.type.enumMember"] = { link = "@constant" },
    ["@lsp.type.interface"] = { link = "@type" },
    ["@lsp.type.macro"] = { link = "@function.macro" },
    ["@lsp.type.method"] = { link = "@function.method" },
    ["@lsp.type.namespace"] = { link = "@module" },
    ["@lsp.type.parameter"] = { link = "@variable.parameter" },
    ["@lsp.type.property"] = { link = "@property" },
    ["@lsp.type.struct"] = { link = "@type" },
    ["@lsp.type.type"] = { link = "@type" },
    ["@lsp.type.typeParameter"] = { link = "@type.definition" },
    ["@lsp.type.variable"] = { link = "@variable" },
    ["@lsp.typemod.function.defaultLibrary"] = { link = "@function.builtin" },
    ["@lsp.typemod.variable.defaultLibrary"] = { link = "@variable.builtin" },
    ["@lsp.typemod.variable.readonly"] = { link = "@constant" },
    ["@lsp.mod.deprecated"] = { strikethrough = true },

    -- gitsigns -------------------------------------------------------------
    GitSignsAdd = { fg = c.green },
    GitSignsChange = { fg = c.blue },
    GitSignsDelete = { fg = c.red },
    GitSignsAddInline = { bg = c.diff_add },
    GitSignsChangeInline = { bg = c.diff_text },
    GitSignsDeleteInline = { bg = c.diff_delete },
    GitSignsCurrentLineBlame = { fg = c.muted, italic = true },

    -- neogit / diffview ----------------------------------------------------
    NeogitBranch = { fg = c.accent, bold = true },
    NeogitRemote = { fg = c.magenta, bold = true },
    NeogitSectionHeader = { fg = c.yellow, bold = true },
    NeogitHunkHeader = { fg = c.fg_light, bg = c.bg_light },
    NeogitHunkHeaderHighlight = { fg = c.accent, bg = c.sel, bold = true },
    NeogitDiffContext = { bg = c.bg },
    NeogitDiffContextHighlight = { bg = c.cursorline },
    NeogitDiffAdd = { fg = c.green, bg = c.diff_add },
    NeogitDiffAddHighlight = { fg = c.bright_green, bg = c.diff_add },
    NeogitDiffDelete = { fg = c.red, bg = c.diff_delete },
    NeogitDiffDeleteHighlight = { fg = c.bright_red, bg = c.diff_delete },
    DiffviewNormal = { fg = c.fg, bg = c.bg_dark },
    DiffviewFilePanelTitle = { fg = c.accent, bold = true },
    DiffviewFilePanelCounter = { fg = c.yellow, bold = true },
    DiffviewFilePanelFileName = { fg = c.fg },
    DiffviewStatusAdded = { fg = c.green },
    DiffviewStatusModified = { fg = c.blue },
    DiffviewStatusDeleted = { fg = c.red },
    DiffviewStatusRenamed = { fg = c.magenta },
    DiffviewFolderName = { fg = c.blue },
    DiffviewFolderSign = { fg = c.brown },

    -- blink.cmp ------------------------------------------------------------
    BlinkCmpMenu = { fg = c.fg_light, bg = c.bg_light },
    BlinkCmpMenuBorder = { fg = c.brown, bg = c.bg_light },
    BlinkCmpMenuSelection = { fg = c.fg_bright, bg = c.sel, bold = true },
    BlinkCmpScrollBarThumb = { bg = c.muted },
    BlinkCmpScrollBarGutter = { bg = c.bg_light },
    BlinkCmpLabel = { fg = c.fg_light, bg = c.bg_light },
    BlinkCmpLabelDeprecated = { fg = c.muted, strikethrough = true },
    BlinkCmpLabelMatch = { fg = c.accent, bold = true },
    BlinkCmpLabelDetail = { fg = c.fg_dark },
    BlinkCmpLabelDescription = { fg = c.muted },
    BlinkCmpKind = { fg = c.cyan },
    BlinkCmpKindText = { fg = c.fg },
    BlinkCmpKindMethod = { fg = c.yellow },
    BlinkCmpKindFunction = { fg = c.yellow },
    BlinkCmpKindConstructor = { fg = c.bright_cyan },
    BlinkCmpKindField = { fg = c.fg_light },
    BlinkCmpKindProperty = { fg = c.fg_light },
    BlinkCmpKindVariable = { fg = c.fg },
    BlinkCmpKindClass = { fg = c.cyan },
    BlinkCmpKindInterface = { fg = c.cyan },
    BlinkCmpKindStruct = { fg = c.cyan },
    BlinkCmpKindModule = { fg = c.magenta },
    BlinkCmpKindKeyword = { fg = c.orange },
    BlinkCmpKindSnippet = { fg = c.green },
    BlinkCmpKindFile = { fg = c.blue },
    BlinkCmpKindFolder = { fg = c.blue },
    BlinkCmpKindConstant = { fg = c.magenta },
    BlinkCmpKindEnum = { fg = c.cyan },
    BlinkCmpKindEnumMember = { fg = c.magenta },
    BlinkCmpDoc = { fg = c.fg, bg = c.bg_light },
    BlinkCmpDocBorder = { fg = c.brown, bg = c.bg_light },
    BlinkCmpDocSeparator = { fg = c.border, bg = c.bg_light },
    BlinkCmpGhostText = { fg = c.muted, italic = true },
    BlinkCmpSignatureHelp = { fg = c.fg, bg = c.bg_light },
    BlinkCmpSignatureHelpBorder = { fg = c.brown, bg = c.bg_light },
    BlinkCmpSignatureHelpActiveParameter = { fg = c.accent, bold = true },

    -- snacks ---------------------------------------------------------------
    SnacksNormal = { fg = c.fg, bg = c.bg_dark },
    SnacksNormalNC = { fg = c.fg, bg = c.bg_dark },
    SnacksWinBar = { fg = c.accent, bg = c.bg_dark, bold = true },
    SnacksWinBarNC = { fg = c.muted, bg = c.bg_dark },
    SnacksBackdrop = { bg = c.bg_darker },
    SnacksIndent = { fg = c.nontext },
    SnacksIndentScope = { fg = c.brown },
    SnacksIndentChunk = { fg = c.brown },
    SnacksPicker = { fg = c.fg, bg = c.bg_dark },
    SnacksPickerBorder = { fg = c.brown, bg = c.bg_dark },
    SnacksPickerTitle = { fg = c.accent, bg = c.bg_dark, bold = true },
    SnacksPickerPrompt = { fg = c.accent, bg = c.bg_dark, bold = true },
    SnacksPickerInputSearch = { fg = c.accent, bg = c.bg_dark },
    SnacksPickerMatch = { fg = c.accent, bold = true },
    SnacksPickerDir = { fg = c.muted },
    SnacksPickerFile = { fg = c.fg },
    SnacksPickerSelected = { fg = c.bright_yellow, bold = true },
    SnacksPickerCursorLine = { bg = c.sel },
    SnacksPickerPathHidden = { fg = c.muted },
    SnacksPickerPathIgnored = { fg = c.muted, italic = true },
    SnacksNotifierInfo = { fg = c.blue, bg = c.bg_light },
    SnacksNotifierWarn = { fg = c.yellow, bg = c.bg_light },
    SnacksNotifierError = { fg = c.red, bg = c.bg_light },
    SnacksNotifierDebug = { fg = c.muted, bg = c.bg_light },
    SnacksNotifierTrace = { fg = c.magenta, bg = c.bg_light },
    SnacksNotifierIconInfo = { fg = c.blue },
    SnacksNotifierIconWarn = { fg = c.yellow },
    SnacksNotifierIconError = { fg = c.red },
    SnacksNotifierTitleInfo = { fg = c.blue, bold = true },
    SnacksNotifierTitleWarn = { fg = c.yellow, bold = true },
    SnacksNotifierTitleError = { fg = c.red, bold = true },
    SnacksNotifierBorderInfo = { fg = c.blue, bg = c.bg_light },
    SnacksNotifierBorderWarn = { fg = c.yellow, bg = c.bg_light },
    SnacksNotifierBorderError = { fg = c.red, bg = c.bg_light },

    -- snacks dashboard: the MAGI splash ------------------------------------
    SnacksDashboardHeader = { fg = c.accent, bold = true },
    SnacksDashboardTitle = { fg = c.accent, bold = true },
    SnacksDashboardSpecial = { fg = c.yellow },
    SnacksDashboardDesc = { fg = c.fg },
    SnacksDashboardIcon = { fg = c.fg },
    SnacksDashboardFile = { fg = c.fg },
    SnacksDashboardDir = { fg = c.fg_dark },
    SnacksDashboardFooter = { fg = c.fg_dark, italic = true },
    SnacksDashboardKey = { fg = c.red, bold = true },

    -- harpoon --------------------------------------------------------------
    HarpoonWindow = { fg = c.fg, bg = c.bg_light },
    HarpoonBorder = { fg = c.brown, bg = c.bg_light },
    HarpoonTitle = { fg = c.accent, bg = c.bg_light, bold = true },
    HarpoonCurrentFile = { fg = c.bright_yellow, bold = true },

    -- lazy / mason ---------------------------------------------------------
    LazyNormal = { fg = c.fg, bg = c.bg_light },
    LazyH1 = { fg = c.bg, bg = c.accent, bold = true },
    LazyH2 = { fg = c.accent, bold = true },
    LazyButton = { fg = c.fg_dark, bg = c.bg_light },
    LazyButtonActive = { fg = c.bg, bg = c.accent, bold = true },
    LazySpecial = { fg = c.accent },
    LazyProgressDone = { fg = c.green, bold = true },
    LazyProgressTodo = { fg = c.muted },
    LazyReasonPlugin = { fg = c.magenta },
    LazyReasonEvent = { fg = c.yellow },
    LazyReasonKeys = { fg = c.cyan },
    LazyReasonStart = { fg = c.green },
    LazyReasonSource = { fg = c.blue },
    LazyReasonFt = { fg = c.bright_blue },
    LazyReasonCmd = { fg = c.bright_yellow },
    MasonNormal = { fg = c.fg, bg = c.bg_light },
    MasonHeader = { fg = c.bg, bg = c.accent, bold = true },
    MasonHighlight = { fg = c.accent },
    MasonHighlightBlock = { fg = c.bg, bg = c.accent },
    MasonHighlightBlockBold = { fg = c.bg, bg = c.accent, bold = true },
    MasonMuted = { fg = c.muted },
    MasonMutedBlock = { fg = c.fg_dark, bg = c.bg_light },
  }
end

local function terminal()
  local t = {
    c.bg_darker, c.red, c.green, c.yellow,
    c.blue, c.magenta, c.cyan, c.fg,
    c.muted, c.bright_red, c.bright_green, c.bright_yellow,
    c.bright_blue, c.bright_magenta, c.bright_cyan, c.fg_bright,
  }
  for i, color in ipairs(t) do
    vim.g["terminal_color_" .. (i - 1)] = color
  end
end

function M.load()
  if vim.g.colors_name then
    vim.cmd.hi("clear")
  end
  vim.o.background = "dark"
  vim.o.termguicolors = true
  vim.g.colors_name = "nerv"

  for name, spec in pairs(groups()) do
    vim.api.nvim_set_hl(0, name, spec)
  end
  terminal()
end

M.palette = c

return M
